{{- if .Values.databricks }}
{{- with .Values.databricks }}

{{- if .serviceAccount.addSA }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ .serviceAccount.name }}
    sa-app: {{ $.Release.Name }}
    project: {{ $.Values.project }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .serviceAccount.name }}-admin
  labels:
    name: {{ .serviceAccount.name }}-admin
    app: {{ $.Release.Name }}
    project: {{ $.Values.project }}
subjects:
  - kind: ServiceAccount
    name: {{ .serviceAccount.name }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
{{- end }}

{{- end }}
{{- end }}
