{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    name: {{ .name }}
    app: {{ .app }}
    project: {{ $.Values.project }}
type: {{ .type }}
{{- if .stringData }}
stringData: {{- toYaml .stringData | nindent 2 }}
{{- end }}
{{- if .data }}
data: {{- toYaml .data | nindent 2 }}
{{- end }}
---
{{ end }}