{{- if .Values.dbservice }}
{{- $partName := "dbservice" }}
{{- with .Values.dbservice }}
{{- if .external.enabled }}

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Release.Name }}-{{ $partName }}
  labels:
    name: {{ $.Release.Name }}-{{ $partName }}
    app: {{ $.Release.Name }}
    project: {{ $.Values.project }}
spec:
  host: "{{ .external.host }}.{{ .external.defaultdns }}"
  path: /
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ $.Release.Name }}-{{ $partName }}
{{- end }}
{{- end }}
{{- end }}