{{- if .Values.jobstorage }}
{{- $partName := "jobstorage" }}
{{- with .Values.jobstorage }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ $partName }}-config
  labels:
    name: {{ $.Release.Name }}-{{ $partName }}-config
    app: {{ $.Release.Name }}
    project: {{ $.Values.project }}
data:
  application.yaml: |
    #
    # Copyright (c) 2022 IBA Group, a.s. All rights reserved.
    #
    # Licensed to the Apache Software Foundation (ASF) under one or more
    # contributor license agreements.  See the NOTICE file distributed with
    # this work for additional information regarding copyright ownership.
    # The ASF licenses this file to You under the Apache License, Version 2.0
    # (the "License"); you may not use this file except in compliance with
    # the License.  You may obtain a copy of the License at
    #
    #   http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.

    # Regardless of where you would run Visual Flow, it's backend API requires a correct application.yaml
    # The purpose of this file is to serve as a guide to structure your own application.yaml
    # Some of these fields have default values assigned to them, that can be changed, others are empty and must be filled in
    server:
      ssl:
        key-store: /tmp/keystore/tls.p12
        key-store-password: ${KEYSTORE_PASS}
        key-store-type: pkcs12
        key-alias: vf-api
        key-password: ${KEYSTORE_PASS}
      host: {{ tpl (.configFile.server.host) $ }}
      port: {{ default "8080" .configFile.server.port }}
      tomcat:
        accesslog:
          enabled: true
      servlet:
        context-path: "{{ default "/vf/be" .subPath }}"
      error:
        include-message: always
        include-binding-errors: always
    spring:
      data:
        redis:
          host: {{ tpl (.configFile.redis.host) $ }}
          port: {{ default "6379" .configFile.redis.port }}
          {{- if .configFile.redis }}
          username: {{ .configFile.redis.username }}
          {{- end }}
          password: {{ .configFile.redis.password }}
          timeout: {{ default "60000" .configFile.redis.timeout }}
          database: {{ default "0" .configFile.redis.database }}
{{- end }}
{{- end }}
