{{- if .Values.historyserv }}
{{- $partName := "historyserv" }}
{{- with .Values.historyserv }}
{{- if eq .external.type "route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Release.Name }}-{{ $partName }}
  labels:
    name: {{ $.Release.Name }}-{{ $partName }}
    app: {{ $.Release.Name }}
    project: {{ $.Values.project }}
spec:
  host: "{{ .external.host }}.{{ .external.defaultdns }}"
  path: {{ default "/" .subPath }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ $.Release.Name }}-{{ $partName }}
{{- end }}

{{- end }}
{{- end }}
