# release name: vf-app-dbs

# helm install redis -f values.yaml bitnami/redis
# helm install pgserver -f values.yaml bitnami/postgresql

bitnami-redis:
  install: true
bitnami-postgresql:
  install: true
