{{- if .Values.backend }}
{{- $partName := "backend" }}
{{- with .Values.backend }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ $partName }}-config
  labels:
    name: {{ $.Release.Name }}-{{ $partName }}-config
    app: {{ $.Release.Name }}
    project: {{ $.Values.project }}
data:
  application.yaml: |
    server:
      ssl:
        key-store: /tmp/keystore/tls.p12
        key-store-password: ${KEYSTORE_PASS}
        key-store-type: pkcs12
        key-alias: vf-api
        key-password: ${KEYSTORE_PASS}
      port: 8080
      tomcat:
        accesslog:
          enabled: true
      servlet:
        context-path: "{{ default "/" .subPath }}"
      error:
        include-message: always
        include-binding-errors: always
    oauth:
      url:
        userInfo: "{{ .configFile.oauth.userInfo }}"
    auth: {{ toYaml .configFile.oauth.fieldsMap | nindent 6 }}
    superusers:
      set:
        {{- if .configFile.superusers }}
        {{- range .configFile.superusers }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
    namespace:
      app: {{ $.Release.Namespace }}
      label: {{ default $.Release.Name .configFile.namespace.label }}
      prefix: {{ default "${namespace.label}-" .configFile.namespace.prefix }}
      {{- if .configFile.namespace.annotations }}
      annotations: {{- toYaml .configFile.namespace.annotations | nindent 8 }}
      {{- end }}
    job:
      imagePullSecret: {{ $.Values.imagePullSecret }}
      spark:
        image: "{{ .configFile.sparkJob.repository }}:{{ .configFile.sparkJob.tag }}"
        serviceAccount: {{ .configFile.sparkJob.jobSA }}
        roleBinding: {{ .configFile.sparkJob.jobRB }}
        master: {{ default "k8s://https://kubernetes.default.svc" .configFile.sparkJob.kubernetesAPI }}
      slack:
        image: "{{ .configFile.slackJob.repository }}:{{ .configFile.slackJob.tag }}"
        apiToken: {{ .configFile.slackJob.appAPItoken }}
    argo: {{- toYaml .configFile.argo | nindent 6 }}
{{- end }}
{{- end }}
