{{- if .Values.backend }}
{{- with .Values.backend }}

{{- if .configFile.sparkJob.addSA }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .configFile.sparkJob.jobSA }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ .configFile.sparkJob.jobSA }}
    sa-app: {{ $.Release.Name }}
    project: {{ $.Values.project }}
imagePullSecrets:
  - name: {{ $.Values.imagePullSecret }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .configFile.sparkJob.jobRB }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ .configFile.sparkJob.jobRB }}
    app: {{ $.Release.Name }}
    project: {{ $.Values.project }}
subjects:
  - kind: ServiceAccount
    name: {{ .configFile.sparkJob.jobSA }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
{{- end }}
---
{{- if .serviceAccount.addSA }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ .serviceAccount.name }}
    sa-app: {{ $.Release.Name }}
    project: {{ $.Values.project }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .serviceAccount.name }}-admin
  labels:
    name: {{ .serviceAccount.name }}-admin
    app: {{ $.Release.Name }}
    project: {{ $.Values.project }}
subjects:
  - kind: ServiceAccount
    name: {{ .serviceAccount.name }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
{{- end }}

{{- end }}
{{- end }}
