# release name: vf-app
vf-app:
  install: true
  backend:
    deployment:
      secretVariables:
        SLACK_API_TOKEN: ""
    configFile:
      superusers:
        - your-github-nickname
      host: https://<HOSTNAME_FROM_SERVICE>:30910/vf/ui/
  frontend:
    deployment:
      variables:
        STRATEGY_CALLBACK_URL: "https://<HOSTNAME_FROM_SERVICE>:30910/vf/ui/callback"
      secretVariables:
        GITHUB_APP_ID: "DUMMY_ID"
        GITHUB_APP_SECRET: "DUMMY_SECRET"
vf-secrets:
  install: true
argo:
  install: true
kube-metrics:
  install: true
